### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sanatgp** [sanatgp/DaggerFFT#1]
- [x] Add AMDGPU support 
- [x] 1D, 2D, 3D, Pencil out-of-place tests
- [x] 1D, 2D, 3D Slab out-of-place tests
